"""empty message

Revision ID: 004949a26ac6
Revises: 
Create Date: 2022-07-05 15:46:22.108802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004949a26ac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_nickname', sa.String(length=50), nullable=False),
    sa.Column('user_password', sa.String(length=75), nullable=False),
    sa.Column('user_register_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
