"""empty message

Revision ID: 0f7275b909bb
Revises: 6ee8d5199c90
Create Date: 2022-07-17 15:46:37.935809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7275b909bb'
down_revision = '6ee8d5199c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=75), nullable=False),
    sa.Column('exprid_datetime', sa.DateTime(), nullable=True),
    sa.Column('token_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=75), nullable=False),
    sa.Column('exprid_datetime', sa.DateTime(), nullable=True),
    sa.Column('token_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_table('gsign')
    # ### end Alembic commands ###
