"""empty message

Revision ID: 1190a79c9a2b
Revises: f281c0c1cb88
Create Date: 2022-07-22 20:29:10.659551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1190a79c9a2b'
down_revision = 'f281c0c1cb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lepton', sa.Column('predict_class', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lepton', 'predict_class')
    # ### end Alembic commands ###
