"""empty message

Revision ID: 129a583681d4
Revises: 2987df82092d
Create Date: 2022-07-20 23:49:11.559604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '129a583681d4'
down_revision = '2987df82092d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lepton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base64_temperature', mysql.LONGTEXT(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lepton')
    # ### end Alembic commands ###
