"""empty message

Revision ID: 39cbf0173357
Revises: 9031be04519d
Create Date: 2022-07-17 17:41:58.542994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cbf0173357'
down_revision = '9031be04519d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('phase', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'phase')
    # ### end Alembic commands ###
