"""empty message

Revision ID: 43f7d76f754f
Revises: 39cbf0173357
Create Date: 2022-07-18 02:33:43.044843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43f7d76f754f'
down_revision = '39cbf0173357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airsign', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_column('airsign', 'uid')
    op.drop_column('gsign', 'token')
    op.drop_column('gsign', 'last_used')
    op.drop_column('gsign', 'exprid_datetime')
    op.drop_column('gsign', 'token_enabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsign', sa.Column('token_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('gsign', sa.Column('exprid_datetime', mysql.DATETIME(), nullable=True))
    op.add_column('gsign', sa.Column('last_used', mysql.DATETIME(), nullable=False))
    op.add_column('gsign', sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=75), nullable=False))
    op.add_column('airsign', sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('airsign', 'account_id')
    # ### end Alembic commands ###
