"""empty message

Revision ID: f281c0c1cb88
Revises: 129a583681d4
Create Date: 2022-07-22 19:54:20.209167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f281c0c1cb88'
down_revision = '129a583681d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lepton', sa.Column('confidence', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lepton', 'confidence')
    # ### end Alembic commands ###
